using System.ComponentModel.DataAnnotations;

namespace Valour.Sdk.Requests;

/// <summary>
/// Request model for initiating OAuth authorization
/// </summary>
public class OauthAuthorizationRequest
{
    /// <summary>
    /// The OAuth app's client ID
    /// </summary>
    [Required]
    public long ClientId { get; set; }

    /// <summary>
    /// The redirect URI that must match the app's registered redirect URL
    /// </summary>
    [Required]
    [Url(ErrorMessage = "Redirect URI must be a valid URL")]
    public string RedirectUri { get; set; }

    /// <summary>
    /// The response type (currently only "code" is supported)
    /// </summary>
    [Required]
    public string ResponseType { get; set; } = "code";

    /// <summary>
    /// The scope of permissions being requested
    /// </summary>
    public long Scope { get; set; }

    /// <summary>
    /// A random string to prevent CSRF attacks
    /// Should be generated by the client and verified on callback
    /// </summary>
    public string? State { get; set; }
}
