using System.Security.Cryptography;
using System.Text;
using Valour.Shared.Models;

namespace Valour.Server.Services;

/// <summary>
/// Rules for push subscriptions. The server sends HTTP requests to Web Push
/// endpoints supplied by clients, so an endpoint is accepted only when it points
/// at a known browser push service over HTTPS. FCM subscriptions carry a device
/// registration token that is handed to the Firebase SDK, never fetched.
/// </summary>
public static class PushSubscriptionPolicy
{
    /// <summary>
    /// Subscriptions kept per user. Registering past this removes the ones
    /// renewed least recently.
    /// </summary>
    public const int MaxSubscriptionsPerUser = 10;

    private const int MaxEndpointLength = 2048;
    private const int MaxFcmTokenLength = 4096;
    private const int MaxKeyLength = 256;

    /// <summary>
    /// Push service hosts used by current browsers: Chromium-based browsers
    /// (FCM), Firefox (Mozilla autopush), Safari (Apple), and Edge (WNS).
    /// </summary>
    private static readonly HashSet<string> WebPushHosts = new(StringComparer.OrdinalIgnoreCase)
    {
        "fcm.googleapis.com",
        "updates.push.services.mozilla.com",
        "web.push.apple.com",
    };

    private static readonly string[] WebPushHostSuffixes =
    {
        ".push.services.mozilla.com",
        ".push.apple.com",
        ".notify.windows.com",
    };

    /// <summary>
    /// Returns null when the subscription may be stored or delivered to,
    /// otherwise a reason suitable for the caller.
    /// </summary>
    public static string Validate(ISharedPushNotificationSubscription subscription)
    {
        if (subscription is null)
            return "Include a subscription.";

        return subscription.DeviceType switch
        {
            NotificationDeviceType.WebPush => ValidateWebPush(subscription),
            NotificationDeviceType.AndroidFcm => IsValidFcmToken(subscription.Endpoint)
                ? null
                : "Invalid device token.",
            _ => "Unsupported device type."
        };
    }

    public static bool IsAllowedWebPushEndpoint(string endpoint)
    {
        if (string.IsNullOrWhiteSpace(endpoint) || endpoint.Length > MaxEndpointLength)
            return false;

        if (!Uri.TryCreate(endpoint, UriKind.Absolute, out var uri))
            return false;

        if (uri.Scheme != Uri.UriSchemeHttps || !uri.IsDefaultPort || !string.IsNullOrEmpty(uri.UserInfo))
            return false;

        var host = uri.IdnHost;
        if (WebPushHosts.Contains(host))
            return true;

        foreach (var suffix in WebPushHostSuffixes)
        {
            if (host.EndsWith(suffix, StringComparison.OrdinalIgnoreCase))
                return true;
        }

        return false;
    }

    public static bool IsValidFcmToken(string token)
    {
        if (string.IsNullOrEmpty(token) || token.Length > MaxFcmTokenLength)
            return false;

        foreach (var c in token)
        {
            if (!(char.IsAsciiLetterOrDigit(c) || c is '-' or '_' or ':'))
                return false;
        }

        return true;
    }

    /// <summary>
    /// True when a registration for an endpoint already held by another account
    /// comes from the same device subscription, which is what happens when a
    /// different account signs in on that browser or device. A Web Push
    /// subscription's keys are generated by the browser and are not derivable
    /// from the endpoint, so matching keys show the caller holds that
    /// subscription. An FCM registration token is itself the device credential.
    /// </summary>
    public static bool IsSameDeviceSubscription(
        ISharedPushNotificationSubscription existing,
        ISharedPushNotificationSubscription incoming)
    {
        if (existing.DeviceType != incoming.DeviceType)
            return false;

        if (incoming.DeviceType == NotificationDeviceType.AndroidFcm)
            return true;

        return FixedTimeEquals(existing.Key, incoming.Key) && FixedTimeEquals(existing.Auth, incoming.Auth);
    }

    private static string ValidateWebPush(ISharedPushNotificationSubscription subscription)
    {
        if (!IsAllowedWebPushEndpoint(subscription.Endpoint))
            return "Push endpoint is not a supported push service.";

        if (!IsValidKey(subscription.Key) || !IsValidKey(subscription.Auth))
            return "Push subscription keys are invalid.";

        return null;
    }

    private static bool IsValidKey(string value)
    {
        if (string.IsNullOrEmpty(value) || value.Length > MaxKeyLength)
            return false;

        // Browsers report keys as base64 or base64url.
        foreach (var c in value)
        {
            if (!(char.IsAsciiLetterOrDigit(c) || c is '+' or '/' or '-' or '_' or '='))
                return false;
        }

        return true;
    }

    private static bool FixedTimeEquals(string left, string right)
    {
        if (string.IsNullOrEmpty(left) || string.IsNullOrEmpty(right))
            return false;

        return CryptographicOperations.FixedTimeEquals(Encoding.UTF8.GetBytes(left), Encoding.UTF8.GetBytes(right));
    }
}
