using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace Valour.Database.Migrations
{
    /// <inheritdoc />
    public partial class MigrateRefactor0 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Idempotent migration using raw SQL with IF NOT EXISTS
            // This allows the migration to run safely even if tables already exist

            // Create all tables (IF NOT EXISTS)
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS automod_actions (
                    id uuid NOT NULL PRIMARY KEY,
                    strikes integer NOT NULL,
                    use_global_strikes boolean NOT NULL,
                    trigger_id uuid NOT NULL,
                    member_added_by bigint NOT NULL,
                    action_type integer NOT NULL,
                    planet_id bigint NOT NULL,
                    target_member_id bigint NOT NULL,
                    message_id bigint,
                    role_id bigint,
                    expires timestamp with time zone,
                    message text
                );

                CREATE TABLE IF NOT EXISTS automod_logs (
                    id uuid NOT NULL PRIMARY KEY,
                    planet_id bigint NOT NULL,
                    trigger_id uuid NOT NULL,
                    member_id bigint NOT NULL,
                    message_id bigint,
                    time_triggered timestamp with time zone NOT NULL
                );

                CREATE TABLE IF NOT EXISTS automod_triggers (
                    id uuid NOT NULL PRIMARY KEY,
                    planet_id bigint NOT NULL,
                    member_added_by bigint NOT NULL,
                    type integer NOT NULL,
                    name text,
                    trigger_words text
                );

                CREATE TABLE IF NOT EXISTS blocked_user_emails (
                    email text NOT NULL PRIMARY KEY
                );

                CREATE TABLE IF NOT EXISTS cdn_bucket_items (
                    id text NOT NULL PRIMARY KEY,
                    hash text NOT NULL,
                    user_id bigint NOT NULL,
                    mime_type text NOT NULL,
                    file_name text NOT NULL,
                    category integer NOT NULL,
                    size_bytes integer NOT NULL,
                    created_at timestamp with time zone NOT NULL
                );

                CREATE TABLE IF NOT EXISTS cdn_proxies (
                    id text NOT NULL PRIMARY KEY,
                    origin text,
                    mime_type text,
                    width integer,
                    height integer
                );

                CREATE TABLE IF NOT EXISTS currencies (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    planet_id bigint NOT NULL,
                    name text,
                    plural_name text,
                    short_code text,
                    symbol text,
                    issued bigint NOT NULL,
                    decimal_places integer NOT NULL,
                    xmin xid NOT NULL
                );

                CREATE TABLE IF NOT EXISTS node_stats (
                    name text NOT NULL PRIMARY KEY,
                    connection_count integer NOT NULL,
                    connection_group_count integer NOT NULL,
                    planet_count integer NOT NULL,
                    active_member_count integer NOT NULL
                );

                CREATE TABLE IF NOT EXISTS notifications (
                    id uuid NOT NULL PRIMARY KEY,
                    user_id bigint NOT NULL,
                    planet_id bigint,
                    channel_id bigint,
                    source_id bigint,
                    source integer NOT NULL,
                    time_sent timestamp with time zone NOT NULL,
                    time_read timestamp with time zone,
                    title text,
                    body text,
                    image_url text,
                    click_url text
                );

                CREATE TABLE IF NOT EXISTS planets (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    owner_id bigint NOT NULL,
                    name text,
                    custom_icon boolean NOT NULL,
                    animated_icon boolean NOT NULL,
                    icon_url text,
                    description text,
                    public boolean NOT NULL,
                    discoverable boolean NOT NULL,
                    is_deleted boolean NOT NULL,
                    has_custom_bg boolean NOT NULL,
                    nsfw boolean NOT NULL,
                    version integer NOT NULL
                );

                CREATE TABLE IF NOT EXISTS reports (
                    id text NOT NULL PRIMARY KEY,
                    time_created timestamp with time zone NOT NULL,
                    reporting_user_id bigint NOT NULL,
                    message_id bigint,
                    channel_id bigint,
                    planet_id bigint,
                    reason_code bigint NOT NULL,
                    long_reason text,
                    reviewed boolean NOT NULL
                );

                CREATE TABLE IF NOT EXISTS stat_objects (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    messages_sent integer NOT NULL,
                    user_count integer NOT NULL,
                    planet_count integer NOT NULL,
                    planet_member_count integer NOT NULL,
                    channel_count integer NOT NULL,
                    category_count integer NOT NULL,
                    message_day_count integer NOT NULL,
                    time_created timestamp with time zone NOT NULL
                );

                CREATE TABLE IF NOT EXISTS tags (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name text,
                    slug varchar(20),
                    created_date timestamp with time zone NOT NULL
                );

                CREATE TABLE IF NOT EXISTS tenor_favorites (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id bigint NOT NULL,
                    tenor_id text
                );

                CREATE TABLE IF NOT EXISTS user_profiles (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    headline text,
                    bio text,
                    border_color text,
                    glow_color text,
                    text_color text,
                    primary_color text,
                    secondary_color text,
                    tertiary_color text,
                    anim_border boolean NOT NULL,
                    bg_image text
                );

                CREATE TABLE IF NOT EXISTS users (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    custom_avatar boolean NOT NULL,
                    animated_avatar boolean NOT NULL,
                    pfp_url text,
                    time_joined timestamp with time zone NOT NULL,
                    name text,
                    bot boolean NOT NULL,
                    disabled boolean NOT NULL,
                    valour_staff boolean NOT NULL,
                    status text,
                    user_state_code integer NOT NULL,
                    time_last_active timestamp with time zone NOT NULL,
                    is_mobile boolean NOT NULL,
                    tag text,
                    compliance boolean NOT NULL,
                    subscription_type text,
                    prior_name text,
                    name_change_time timestamp with time zone,
                    version integer NOT NULL DEFAULT 0,
                    tutorial_state bigint NOT NULL DEFAULT 0
                );

                CREATE TABLE IF NOT EXISTS channels (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name text,
                    description text,
                    channel_type integer NOT NULL,
                    last_update_time timestamp with time zone NOT NULL,
                    is_deleted boolean NOT NULL,
                    planet_id bigint,
                    parent_id bigint,
                    position bigint NOT NULL,
                    inherits_perms boolean NOT NULL,
                    is_default boolean NOT NULL,
                    version integer NOT NULL
                );

                CREATE TABLE IF NOT EXISTS planet_bans (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    planet_id bigint NOT NULL,
                    issuer_id bigint NOT NULL,
                    target_id bigint NOT NULL,
                    reason text,
                    time_created timestamp with time zone NOT NULL,
                    time_expires timestamp with time zone
                );

                CREATE TABLE IF NOT EXISTS planet_invites (
                    code text NOT NULL PRIMARY KEY,
                    planet_id bigint NOT NULL,
                    issuer_id bigint NOT NULL,
                    time_created timestamp with time zone NOT NULL,
                    time_expires timestamp with time zone
                );

                CREATE TABLE IF NOT EXISTS planet_roles (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    local_index integer NOT NULL,
                    is_admin boolean NOT NULL,
                    planet_id bigint NOT NULL,
                    position bigint NOT NULL,
                    is_default boolean NOT NULL,
                    permissions bigint NOT NULL,
                    chat_perms bigint NOT NULL,
                    cat_perms bigint NOT NULL,
                    voice_perms bigint NOT NULL,
                    color text,
                    bold boolean NOT NULL,
                    italics boolean NOT NULL,
                    name text,
                    anyone_can_mention boolean NOT NULL,
                    version integer NOT NULL
                );

                CREATE TABLE IF NOT EXISTS planet_tags (
                    planet_id bigint NOT NULL,
                    tag_id bigint NOT NULL,
                    PRIMARY KEY (planet_id, tag_id)
                );

                CREATE TABLE IF NOT EXISTS auth_tokens (
                    id text NOT NULL PRIMARY KEY,
                    app_id text,
                    user_id bigint NOT NULL,
                    scope bigint NOT NULL,
                    time_created timestamp with time zone NOT NULL,
                    time_expires timestamp with time zone NOT NULL,
                    issued_address text
                );

                CREATE TABLE IF NOT EXISTS credentials (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id bigint NOT NULL,
                    credential_type text,
                    identifier text,
                    secret bytea,
                    salt bytea
                );

                CREATE TABLE IF NOT EXISTS email_confirm_codes (
                    code text NOT NULL PRIMARY KEY,
                    user_id bigint NOT NULL
                );

                CREATE TABLE IF NOT EXISTS multi_auth (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id bigint NOT NULL,
                    type text,
                    secret text,
                    verified boolean NOT NULL,
                    created_at timestamp with time zone NOT NULL
                );

                CREATE TABLE IF NOT EXISTS notification_subscriptions (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    device_type integer NOT NULL,
                    expires_at timestamp with time zone NOT NULL DEFAULT (NOW() + INTERVAL '7 days'),
                    user_id bigint NOT NULL,
                    endpoint text NOT NULL,
                    key text,
                    auth text
                );

                CREATE TABLE IF NOT EXISTS oauth_apps (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    secret text,
                    owner_id bigint NOT NULL,
                    uses integer NOT NULL,
                    image_url text,
                    name text,
                    redirect_url text
                );

                CREATE TABLE IF NOT EXISTS password_recoveries (
                    code text NOT NULL PRIMARY KEY,
                    user_id bigint NOT NULL
                );

                CREATE TABLE IF NOT EXISTS planet_members (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id bigint NOT NULL,
                    planet_id bigint NOT NULL,
                    nickname varchar(32),
                    member_pfp text,
                    is_deleted boolean NOT NULL,
                    rf0 bigint NOT NULL,
                    rf1 bigint NOT NULL,
                    rf2 bigint NOT NULL,
                    rf3 bigint NOT NULL
                );

                CREATE TABLE IF NOT EXISTS referrals (
                    user_id bigint NOT NULL PRIMARY KEY,
                    referrer_id bigint NOT NULL,
                    created timestamp with time zone NOT NULL,
                    reward numeric NOT NULL
                );

                CREATE TABLE IF NOT EXISTS themes (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    author_id bigint NOT NULL,
                    name text,
                    description text,
                    custom_banner boolean NOT NULL,
                    animated_banner boolean NOT NULL,
                    published boolean NOT NULL,
                    font_color text,
                    font_alt_color text,
                    link_color text,
                    main_color_1 text,
                    main_color_2 text,
                    main_color_3 text,
                    main_color_4 text,
                    main_color_5 text,
                    tint_color text,
                    vibrant_purple text,
                    vibrant_blue text,
                    vibrant_cyan text,
                    pastel_cyan text,
                    pastel_cyan_purple text,
                    pastel_purple text,
                    pastel_red text,
                    custom_css text
                );

                CREATE TABLE IF NOT EXISTS user_emails (
                    email text NOT NULL PRIMARY KEY,
                    verified boolean NOT NULL,
                    user_id bigint NOT NULL,
                    birth_date timestamp with time zone,
                    locality integer,
                    join_invite_code text,
                    join_source text
                );

                CREATE TABLE IF NOT EXISTS user_friends (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id bigint NOT NULL,
                    friend_id bigint NOT NULL
                );

                CREATE TABLE IF NOT EXISTS user_subscriptions (
                    id text NOT NULL PRIMARY KEY,
                    user_id bigint NOT NULL,
                    type text,
                    created timestamp with time zone NOT NULL,
                    last_charged timestamp with time zone NOT NULL,
                    active boolean NOT NULL,
                    cancelled boolean NOT NULL,
                    renewals integer NOT NULL
                );

                CREATE TABLE IF NOT EXISTS channel_members (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    channel_id bigint NOT NULL,
                    user_id bigint NOT NULL
                );

                CREATE TABLE IF NOT EXISTS permissions_nodes (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    planet_id bigint NOT NULL,
                    code bigint NOT NULL,
                    mask bigint NOT NULL,
                    role_id bigint NOT NULL,
                    target_id bigint NOT NULL,
                    target_type integer NOT NULL
                );

                CREATE TABLE IF NOT EXISTS eco_accounts (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name text,
                    account_type integer NOT NULL,
                    user_id bigint NOT NULL,
                    planet_id bigint NOT NULL,
                    planet_member_id bigint,
                    currency_id bigint NOT NULL,
                    balance_value numeric NOT NULL,
                    xmin xid NOT NULL
                );

                CREATE TABLE IF NOT EXISTS messages (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    planet_id bigint,
                    reply_to_id bigint,
                    author_user_id bigint NOT NULL,
                    author_member_id bigint,
                    content text,
                    time_sent timestamp with time zone NOT NULL,
                    channel_id bigint NOT NULL,
                    embed_data text,
                    mentions_data text,
                    attachments_data text,
                    edit_time timestamp with time zone
                );

                CREATE TABLE IF NOT EXISTS planet_role_members (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id bigint NOT NULL,
                    role_id bigint NOT NULL,
                    member_id bigint NOT NULL,
                    planet_id bigint NOT NULL
                );

                CREATE TABLE IF NOT EXISTS user_channel_states (
                    channel_id bigint NOT NULL,
                    user_id bigint NOT NULL,
                    planet_id bigint,
                    member_id bigint,
                    last_viewed_time timestamp with time zone NOT NULL,
                    PRIMARY KEY (user_id, channel_id)
                );

                CREATE TABLE IF NOT EXISTS theme_votes (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    theme_id bigint NOT NULL,
                    user_id bigint NOT NULL,
                    sentiment boolean NOT NULL,
                    created_at timestamp with time zone NOT NULL
                );

                CREATE TABLE IF NOT EXISTS transactions (
                    id text NOT NULL PRIMARY KEY,
                    planet_id bigint NOT NULL,
                    user_from_id bigint NOT NULL,
                    account_from_id bigint NOT NULL,
                    user_to_id bigint NOT NULL,
                    account_to_id bigint NOT NULL,
                    time_stamp timestamp with time zone NOT NULL,
                    description text,
                    amount numeric NOT NULL,
                    data text,
                    fingerprint text,
                    forced_by bigint
                );

                CREATE TABLE IF NOT EXISTS message_reactions (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    emoji text NOT NULL,
                    message_id bigint NOT NULL,
                    author_user_id bigint NOT NULL,
                    author_member_id bigint,
                    created_at timestamp with time zone NOT NULL
                );
            ");

            // Insert seed data (ON CONFLICT DO NOTHING)
            migrationBuilder.Sql(@"
                INSERT INTO tags (id, created_date, name, slug) VALUES
                    (1, '2025-08-20 00:00:00+00', 'Gaming', 'gaming'),
                    (2, '2025-08-20 00:00:00+00', 'Anime', 'anime'),
                    (3, '2025-08-20 00:00:00+00', 'Debates', 'debates'),
                    (4, '2025-08-20 00:00:00+00', 'News', 'news'),
                    (5, '2025-08-20 00:00:00+00', 'Strategy', 'strategy'),
                    (6, '2025-08-20 00:00:00+00', 'Action', 'action'),
                    (7, '2025-08-20 00:00:00+00', 'Manga', 'manga'),
                    (8, '2025-08-20 00:00:00+00', 'Geek Culture', 'geek-culture'),
                    (9, '2025-08-20 00:00:00+00', 'Events', 'events'),
                    (10, '2025-08-20 00:00:00+00', 'Indie Games', 'indie-games')
                ON CONFLICT (id) DO NOTHING;
            ");

            // Create all indexes (IF NOT EXISTS)
            migrationBuilder.Sql(@"
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_auth_tokens_id"" ON auth_tokens (id);
                CREATE INDEX IF NOT EXISTS ""IX_auth_tokens_scope"" ON auth_tokens (scope);
                CREATE INDEX IF NOT EXISTS ""IX_auth_tokens_user_id"" ON auth_tokens (user_id);
                CREATE INDEX IF NOT EXISTS ""IX_automod_actions_planet_id"" ON automod_actions (planet_id);
                CREATE INDEX IF NOT EXISTS ""IX_automod_actions_trigger_id"" ON automod_actions (trigger_id);
                CREATE INDEX IF NOT EXISTS ""IX_automod_logs_member_id"" ON automod_logs (member_id);
                CREATE INDEX IF NOT EXISTS ""IX_automod_logs_planet_id"" ON automod_logs (planet_id);
                CREATE INDEX IF NOT EXISTS ""IX_automod_logs_trigger_id"" ON automod_logs (trigger_id);
                CREATE INDEX IF NOT EXISTS ""IX_automod_triggers_planet_id"" ON automod_triggers (planet_id);
                CREATE INDEX IF NOT EXISTS ""IX_channel_members_channel_id"" ON channel_members (channel_id);
                CREATE INDEX IF NOT EXISTS ""IX_channel_members_user_id"" ON channel_members (user_id);
                CREATE INDEX IF NOT EXISTS ""IX_channels_is_deleted"" ON channels (is_deleted);
                CREATE INDEX IF NOT EXISTS ""IX_channels_parent_id"" ON channels (parent_id);
                CREATE INDEX IF NOT EXISTS ""IX_channels_planet_id"" ON channels (planet_id);
                CREATE INDEX IF NOT EXISTS ""IX_channels_position"" ON channels (position);
                CREATE INDEX IF NOT EXISTS ""IX_credentials_user_id"" ON credentials (user_id);
                CREATE INDEX IF NOT EXISTS ""IX_eco_accounts_planet_member_id"" ON eco_accounts (planet_member_id);
                CREATE INDEX IF NOT EXISTS ""IX_eco_accounts_user_id"" ON eco_accounts (user_id);
                CREATE INDEX IF NOT EXISTS ""IX_email_confirm_codes_user_id"" ON email_confirm_codes (user_id);
                CREATE INDEX IF NOT EXISTS ""IX_message_reactions_author_member_id"" ON message_reactions (author_member_id);
                CREATE INDEX IF NOT EXISTS ""IX_message_reactions_author_user_id"" ON message_reactions (author_user_id);
                CREATE INDEX IF NOT EXISTS ""IX_message_reactions_message_id"" ON message_reactions (message_id);
                CREATE INDEX IF NOT EXISTS ""IX_messages_author_member_id"" ON messages (author_member_id);
                CREATE INDEX IF NOT EXISTS ""IX_messages_author_user_id"" ON messages (author_user_id);
                CREATE INDEX IF NOT EXISTS ""IX_messages_channel_id"" ON messages (channel_id);
                CREATE INDEX IF NOT EXISTS ""IX_messages_planet_id"" ON messages (planet_id);
                CREATE INDEX IF NOT EXISTS ""IX_messages_reply_to_id"" ON messages (reply_to_id);
                CREATE INDEX IF NOT EXISTS ""IX_multi_auth_user_id"" ON multi_auth (user_id);
                CREATE INDEX IF NOT EXISTS ""IX_notification_subscriptions_user_id"" ON notification_subscriptions (user_id);
                CREATE INDEX IF NOT EXISTS ""IX_oauth_apps_owner_id"" ON oauth_apps (owner_id);
                CREATE INDEX IF NOT EXISTS ""IX_password_recoveries_user_id"" ON password_recoveries (user_id);
                CREATE INDEX IF NOT EXISTS ""IX_permissions_nodes_planet_id"" ON permissions_nodes (planet_id);
                CREATE INDEX IF NOT EXISTS ""IX_permissions_nodes_role_id"" ON permissions_nodes (role_id);
                CREATE INDEX IF NOT EXISTS ""IX_permissions_nodes_target_id"" ON permissions_nodes (target_id);
                CREATE INDEX IF NOT EXISTS ""IX_planet_bans_planet_id"" ON planet_bans (planet_id);
                CREATE INDEX IF NOT EXISTS ""IX_planet_invites_issuer_id"" ON planet_invites (issuer_id);
                CREATE INDEX IF NOT EXISTS ""IX_planet_invites_planet_id"" ON planet_invites (planet_id);
                CREATE INDEX IF NOT EXISTS ""IX_planet_invites_time_created_time_expires"" ON planet_invites (time_created, time_expires);
                CREATE INDEX IF NOT EXISTS ""IX_planet_members_planet_id"" ON planet_members (planet_id);
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_planet_members_user_id_planet_id"" ON planet_members (user_id, planet_id);
                CREATE INDEX IF NOT EXISTS ""IX_planet_role_members_member_id"" ON planet_role_members (member_id);
                CREATE INDEX IF NOT EXISTS ""IX_planet_role_members_role_id"" ON planet_role_members (role_id);
                CREATE INDEX IF NOT EXISTS ""IX_planet_roles_planet_id"" ON planet_roles (planet_id);
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_planet_roles_planet_id_id"" ON planet_roles (planet_id, id);
                CREATE INDEX IF NOT EXISTS ""IX_planet_tags_tag_id"" ON planet_tags (tag_id);
                CREATE INDEX IF NOT EXISTS ""IX_referrals_referrer_id"" ON referrals (referrer_id);
                CREATE INDEX IF NOT EXISTS ""IX_referrals_user_id"" ON referrals (user_id);
                CREATE INDEX IF NOT EXISTS ""IX_reports_channel_id"" ON reports (channel_id);
                CREATE INDEX IF NOT EXISTS ""IX_reports_message_id"" ON reports (message_id);
                CREATE INDEX IF NOT EXISTS ""IX_reports_planet_id"" ON reports (planet_id);
                CREATE INDEX IF NOT EXISTS ""IX_reports_reporting_user_id"" ON reports (reporting_user_id);
                CREATE INDEX IF NOT EXISTS ""IX_theme_votes_theme_id"" ON theme_votes (theme_id);
                CREATE INDEX IF NOT EXISTS ""IX_theme_votes_user_id"" ON theme_votes (user_id);
                CREATE INDEX IF NOT EXISTS ""IX_themes_author_id"" ON themes (author_id);
                CREATE INDEX IF NOT EXISTS ""IX_transactions_account_from_id"" ON transactions (account_from_id);
                CREATE INDEX IF NOT EXISTS ""IX_transactions_account_to_id"" ON transactions (account_to_id);
                CREATE INDEX IF NOT EXISTS ""IX_transactions_planet_id"" ON transactions (planet_id);
                CREATE INDEX IF NOT EXISTS ""IX_transactions_user_from_id"" ON transactions (user_from_id);
                CREATE INDEX IF NOT EXISTS ""IX_transactions_user_to_id"" ON transactions (user_to_id);
                CREATE INDEX IF NOT EXISTS ""IX_user_channel_states_channel_id"" ON user_channel_states (channel_id);
                CREATE INDEX IF NOT EXISTS ""IX_user_channel_states_member_id"" ON user_channel_states (member_id);
                CREATE INDEX IF NOT EXISTS ""IX_user_channel_states_planet_id"" ON user_channel_states (planet_id);
                CREATE INDEX IF NOT EXISTS ""IX_user_channel_states_user_id"" ON user_channel_states (user_id);
                CREATE INDEX IF NOT EXISTS ""IX_user_emails_birth_date"" ON user_emails (birth_date);
                CREATE INDEX IF NOT EXISTS ""IX_user_emails_email"" ON user_emails (email);
                CREATE INDEX IF NOT EXISTS ""IX_user_emails_join_invite_code"" ON user_emails (join_invite_code);
                CREATE INDEX IF NOT EXISTS ""IX_user_emails_locality"" ON user_emails (locality);
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_user_emails_user_id"" ON user_emails (user_id);
                CREATE INDEX IF NOT EXISTS ""IX_user_friends_friend_id"" ON user_friends (friend_id);
                CREATE INDEX IF NOT EXISTS ""IX_user_friends_user_id"" ON user_friends (user_id);
                CREATE INDEX IF NOT EXISTS ""IX_user_subscriptions_user_id"" ON user_subscriptions (user_id);
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_users_tag_name"" ON users (tag, name);
                CREATE INDEX IF NOT EXISTS ""IX_users_time_last_active"" ON users (time_last_active);
            ");

            // Add foreign keys (only if they don't exist)
            migrationBuilder.Sql(@"
                DO $$ BEGIN
                    ALTER TABLE channels ADD CONSTRAINT ""FK_channels_channels_parent_id"" FOREIGN KEY (parent_id) REFERENCES channels(id);
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE channels ADD CONSTRAINT ""FK_channels_planets_planet_id"" FOREIGN KEY (planet_id) REFERENCES planets(id);
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE planet_bans ADD CONSTRAINT ""FK_planet_bans_planets_planet_id"" FOREIGN KEY (planet_id) REFERENCES planets(id) ON DELETE CASCADE;
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE planet_invites ADD CONSTRAINT ""FK_planet_invites_planets_planet_id"" FOREIGN KEY (planet_id) REFERENCES planets(id) ON DELETE CASCADE;
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE planet_roles ADD CONSTRAINT ""FK_planet_roles_planets_planet_id"" FOREIGN KEY (planet_id) REFERENCES planets(id) ON DELETE CASCADE;
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE planet_tags ADD CONSTRAINT ""fk_planet_tag_planet_id"" FOREIGN KEY (planet_id) REFERENCES planets(id) ON DELETE CASCADE;
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE planet_tags ADD CONSTRAINT ""fk_planet_tag_tag_id"" FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE;
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE auth_tokens ADD CONSTRAINT ""FK_auth_tokens_users_user_id"" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE credentials ADD CONSTRAINT ""FK_credentials_users_user_id"" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE email_confirm_codes ADD CONSTRAINT ""FK_email_confirm_codes_users_user_id"" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE multi_auth ADD CONSTRAINT ""FK_multi_auth_users_user_id"" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE notification_subscriptions ADD CONSTRAINT ""FK_notification_subscriptions_users_user_id"" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE oauth_apps ADD CONSTRAINT ""FK_oauth_apps_users_owner_id"" FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE;
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE password_recoveries ADD CONSTRAINT ""FK_password_recoveries_users_user_id"" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE planet_members ADD CONSTRAINT ""FK_planet_members_planets_planet_id"" FOREIGN KEY (planet_id) REFERENCES planets(id) ON DELETE CASCADE;
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE planet_members ADD CONSTRAINT ""FK_planet_members_users_user_id"" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE referrals ADD CONSTRAINT ""FK_referrals_users_referrer_id"" FOREIGN KEY (referrer_id) REFERENCES users(id) ON DELETE CASCADE;
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE referrals ADD CONSTRAINT ""FK_referrals_users_user_id"" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE themes ADD CONSTRAINT ""FK_themes_users_author_id"" FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE CASCADE;
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE user_emails ADD CONSTRAINT ""FK_user_emails_users_user_id"" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE user_friends ADD CONSTRAINT ""FK_user_friends_users_friend_id"" FOREIGN KEY (friend_id) REFERENCES users(id) ON DELETE CASCADE;
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE user_friends ADD CONSTRAINT ""FK_user_friends_users_user_id"" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE user_subscriptions ADD CONSTRAINT ""FK_user_subscriptions_users_user_id"" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE channel_members ADD CONSTRAINT ""FK_channel_members_channels_channel_id"" FOREIGN KEY (channel_id) REFERENCES channels(id) ON DELETE CASCADE;
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE channel_members ADD CONSTRAINT ""FK_channel_members_users_user_id"" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE permissions_nodes ADD CONSTRAINT ""FK_permissions_nodes_channels_target_id"" FOREIGN KEY (target_id) REFERENCES channels(id) ON DELETE CASCADE NOT VALID;
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE permissions_nodes ADD CONSTRAINT ""FK_permissions_nodes_planet_roles_role_id"" FOREIGN KEY (role_id) REFERENCES planet_roles(id) ON DELETE CASCADE;
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE permissions_nodes ADD CONSTRAINT ""FK_permissions_nodes_planets_planet_id"" FOREIGN KEY (planet_id) REFERENCES planets(id) ON DELETE CASCADE;
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE eco_accounts ADD CONSTRAINT ""FK_eco_accounts_planet_members_planet_member_id"" FOREIGN KEY (planet_member_id) REFERENCES planet_members(id);
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE eco_accounts ADD CONSTRAINT ""FK_eco_accounts_users_user_id"" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE messages ADD CONSTRAINT ""FK_messages_channels_channel_id"" FOREIGN KEY (channel_id) REFERENCES channels(id) ON DELETE CASCADE;
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE messages ADD CONSTRAINT ""FK_messages_messages_reply_to_id"" FOREIGN KEY (reply_to_id) REFERENCES messages(id);
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE messages ADD CONSTRAINT ""FK_messages_planet_members_author_member_id"" FOREIGN KEY (author_member_id) REFERENCES planet_members(id);
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE messages ADD CONSTRAINT ""FK_messages_planets_planet_id"" FOREIGN KEY (planet_id) REFERENCES planets(id);
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE messages ADD CONSTRAINT ""FK_messages_users_author_user_id"" FOREIGN KEY (author_user_id) REFERENCES users(id) ON DELETE CASCADE;
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE planet_role_members ADD CONSTRAINT ""FK_planet_role_members_planet_members_member_id"" FOREIGN KEY (member_id) REFERENCES planet_members(id) ON DELETE CASCADE;
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE planet_role_members ADD CONSTRAINT ""FK_planet_role_members_planet_roles_role_id"" FOREIGN KEY (role_id) REFERENCES planet_roles(id) ON DELETE CASCADE;
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE user_channel_states ADD CONSTRAINT ""FK_user_channel_states_channels_channel_id"" FOREIGN KEY (channel_id) REFERENCES channels(id) ON DELETE CASCADE;
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE user_channel_states ADD CONSTRAINT ""FK_user_channel_states_planet_members_member_id"" FOREIGN KEY (member_id) REFERENCES planet_members(id);
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE user_channel_states ADD CONSTRAINT ""FK_user_channel_states_planets_planet_id"" FOREIGN KEY (planet_id) REFERENCES planets(id);
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE user_channel_states ADD CONSTRAINT ""FK_user_channel_states_users_user_id"" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE theme_votes ADD CONSTRAINT ""FK_theme_votes_themes_theme_id"" FOREIGN KEY (theme_id) REFERENCES themes(id) ON DELETE CASCADE;
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE theme_votes ADD CONSTRAINT ""FK_theme_votes_users_user_id"" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE transactions ADD CONSTRAINT ""FK_transactions_eco_accounts_account_from_id"" FOREIGN KEY (account_from_id) REFERENCES eco_accounts(id) ON DELETE CASCADE;
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE transactions ADD CONSTRAINT ""FK_transactions_eco_accounts_account_to_id"" FOREIGN KEY (account_to_id) REFERENCES eco_accounts(id) ON DELETE CASCADE;
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE transactions ADD CONSTRAINT ""FK_transactions_planets_planet_id"" FOREIGN KEY (planet_id) REFERENCES planets(id) ON DELETE CASCADE;
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE transactions ADD CONSTRAINT ""FK_transactions_users_user_from_id"" FOREIGN KEY (user_from_id) REFERENCES users(id) ON DELETE CASCADE;
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE transactions ADD CONSTRAINT ""FK_transactions_users_user_to_id"" FOREIGN KEY (user_to_id) REFERENCES users(id) ON DELETE CASCADE;
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE message_reactions ADD CONSTRAINT ""FK_message_reactions_messages_message_id"" FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE CASCADE;
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE message_reactions ADD CONSTRAINT ""FK_message_reactions_planet_members_author_member_id"" FOREIGN KEY (author_member_id) REFERENCES planet_members(id);
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;

                DO $$ BEGIN
                    ALTER TABLE message_reactions ADD CONSTRAINT ""FK_message_reactions_users_author_user_id"" FOREIGN KEY (author_user_id) REFERENCES users(id) ON DELETE CASCADE;
                EXCEPTION WHEN duplicate_object THEN NULL; END $$;
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // No-op: We don't want to drop tables on rollback
        }
    }
}
